return {
  cmd = { "rime_ls" },
  -- cmd = { '/home/wlh/coding/rime-ls/target/debug/rime_ls' },
  -- -- cmd = { '/home/wlh/coding/rime-ls/target/release/rime_ls' },
  -- cmd = vim.lsp.rpc.connect("127.0.0.1", 9257),
  filetypes = { "markdown" },
  init_options = {
    enabled = vim.g.rime_enabled,
    shared_data_dir = "/usr/share/rime-data",
    user_data_dir = "~/.local/share/rime-ls",
    log_dir = "/tmp",
    max_candidates = 9,
    paging_characters = { ",", "." },
    trigger_characters = {},
    schema_trigger_character = "&",
    max_tokens = 0,
    always_incomplete = true,
    preselect_first = false,
    show_filter_text_in_label = false,
    long_filter_text = true,
  },
}
