-- require "render-markdown".setup {
--   latex = {
--     enabled = false,
--   },
--   heading = {
--     icons = { "◉ ", "◎ ", "○ ", "✺ ", "▶ ", "⤷ " },
--   },
-- }
--
-- require "livepreview.config".set {}
