-- vim.g.rime_enabled = false
-- local rime_on_attach = function(client, _)
-- 	client.request("workspace/executeCommand", { command = "rime-ls.toggle-rime" }, function(_, result, ctx, _)
-- 		if ctx.client_id == client.id then
-- 			vim.g.rime_enabled = result
-- 		end
-- 	end)
-- 	vim.keymap.set("n", "<leader>rr", function()
-- 		client.request("workspace/executeCommand", { command = "rime-ls.toggle-rime" }, function(_, result, ctx, _)
-- 			if ctx.client_id == client.id then
-- 				vim.g.rime_enabled = result
-- 			end
-- 		end)
-- 	end)
-- 	-- vim.keymap.set("n", "<leader>rs", function()
-- 	-- 	vim.lsp.buf.execute_command({ command = "rime-ls.sync-user-data" })
-- 	-- end)
-- end
--
-- if vim.fs.root(0, "index.norg") then
-- 	vim.lsp.start({
-- 		name = "rime-ls",
-- 		cmd = { "rime_ls" },
-- 		init_options = {
-- 			enabled = vim.g.rime_enabled,
-- 			shared_data_dir = "/usr/share/rime-data",
-- 			user_data_dir = "~/.local/share/rime-ls",
-- 			log_dir = "~/.local/share/rime-ls",
-- 			max_candidates = 9,
-- 			trigger_characters = {},
-- 			schema_trigger_character = "&", -- [since v0.2.0] 当输入此字符串时请求补全会触发 “方案选单”
-- 		},
-- 		on_attach = rime_on_attach,
-- 	})
-- end
